--- 
- name: Show a fact returned by a module
  hosts: debian
  gather_facts: false
  tasks: 
    - name: Get service Facts
      service_facts:

    - debug: var=ansible_facts['services']['sshd.service']
...